// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zldflksqnbyzunxqwxlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsZGZsa3NxbmJ5enVueHF3eGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzQxNjksImV4cCI6MjA1OTIxMDE2OX0.Z6k00ZbkDDfc3W90-cq8JznGtH8Y2cvvgIdZ10oFYII";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);